version: '3.8'

services:
  app:
    image: python:3.8-slim
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install flask && python open_restaurants.py"
    ports:
      - "8000:8000"


